-   id: textlint
    name: textlint
    description: ''
    entry: textlint
    language: node
    'types': [markdown]
    args: []
    require_serial: false
    additional_dependencies: ["textlint@14.6.0"]
    minimum_pre_commit_version: '0'
-   id: textlint-fix
    name: textlint-fix
    description: ''
    entry: textlint
    language: node
    'types': [markdown]
    args: ["--fix"]
    require_serial: false
    additional_dependencies: ["textlint@14.6.0"]
    minimum_pre_commit_version: '0'