-   id: textlint
    name: textlint
    description: ''
    entry: textlint
    language: node
    'types': [markdown]
    args: []
    require_serial: false
    additional_dependencies: ["textlint@11.8.3"]
    minimum_pre_commit_version: '0'
